gamescope-3.15.1-2
Archive sha256sum: 8a2fdba73b24a6c1ee28d89d2f80fed39750d04a66adfc42e3747efbf5525bd8 jupiter-3.9/gamescope-3.15.1-2.src.tar.gz

diff --git a/gamescope-session b/gamescope-session
--- a/gamescope-session
+++ b/gamescope-session
@@ -62,24 +62,6 @@ export WINE_CPU_TOPOLOGY=8:0,1,2,3,4,5,6,7
 # To expose vram info from radv's patch we're including
 export WINEDLLOVERRIDES=dxgi=n
 
-# Workaround for steam getting killed immediatly during reboot
-# See: jupiter/tasks/-/issues/280
-export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
-if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-reboot-now
-	sudo -n reboot
-fi
-
-# Workaround for steam getting killed immediatly during shutdown
-# Same idea as reboot sentinel above
-export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
-if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-poweroff-now
-	sudo -n poweroff
-fi
-
 # Enable dynamic backlight, we have the kernel patch to disable events
 export STEAM_ENABLE_DYNAMIC_BACKLIGHT=1
 
@@ -261,6 +243,68 @@ else
 	echo >&2 "!! Failed to claim global gamescope stats session"
 fi
 
+cleanup_loop() {
+    if [ -n "$pid" ]; then
+        kill "$pid"
+    fi
+    exit 0
+}
+
+# Make sure we stop the loop and cleanup properly, with a wait for our
+# children, when we have a recurring background command.
+loop_background() {
+    (
+        pid=
+        trap cleanup_loop TERM
+        while true; do
+            "$@" &
+            pid=$!
+            wait "$pid"
+        done
+    ) &
+}
+
+print_children() {
+    ps h -o pid --ppid "$1" | sed 's/^[[:space:]]*//'
+}
+
+send_signals() {
+    kill -TERM "$@"
+}
+
+cleanup() {
+    local timeout="$1"
+    shift
+    local children=("$@")
+    local sleep_pid pid ret
+
+    # Start a background sleep as a timeout because we don't trust it
+    sleep "$timeout" &
+    sleep_pid=$!
+
+    for pid in "${children[@]}"; do
+        if ! kill -0 "$pid" 2>/dev/null; then
+            continue
+        fi
+
+        # Wait for child or the sleep to finish for timeout purposes
+        ret=0
+        wait -np finished_pid "$pid" "$sleep_pid" || ret=$?
+
+        # Our sleep command finished; we timed out
+        if [[ "$finished_pid" == "$sleep_pid" ]]; then
+            return 2
+        fi
+
+        # Signal received by wait when already in cleanup; bail out
+        if (( ret > 128 )); then
+            return 1
+        fi
+    done
+
+    kill "$sleep_pid"
+}
+
 gamescope \
 	--generate-drm-mode fixed \
 	--xwayland-count 2 \
@@ -286,19 +330,16 @@ else
 	# SDDM will restart us
 fi
 
-xbindkeys -f /etc/xbindkeysrc
+xbindkeys -n -f /etc/xbindkeysrc &
 
 steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
 
 # Input method support
-/usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+/usr/bin/ibus-daemon -r --panel=disable --emoji-extension=disable &
 
 # steamargs+=("-steamfs")
 
-(while true; do
-    /usr/lib/hwsupport/powerbuttond
-done) &
-
+loop_background /usr/lib/hwsupport/powerbuttond
 
 short_session_tracker_file="/tmp/steamos-short-session-tracker"
 short_session_duration=60
@@ -328,20 +369,40 @@ if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
 	rm "$short_session_tracker_file"
 fi
 
+steam_notif_daemon &
+galileo-mura-setup &
+loop_background mangoapp
+
 if [[ -x $HOME/devkit-game/devkit-steam ]]; then
-	steam_notif_daemon &
-	galileo-mura-setup &
-	(while true; do
-		mangoapp
-	done) &
-	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
+	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
 else
-	steam_notif_daemon &
-	galileo-mura-setup &
-	(while true; do
-		mangoapp
-	done) &
-	steam "${steamargs[@]}"
+	steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
+fi
+
+kill_steam() {
+	# We need to kill the children of the wrapper, since the wrapper
+	# lacks signal handling (and so killing it does not properly kill
+	# steam)
+	readarray -t pids < <(print_children "$steam_wrapper_pid")
+
+	if [[ "${#pids[@]}" -gt 0 ]]; then
+		kill -TERM "${pids[@]}"
+	else
+		kill -TERM "$steam_wrapper_pid"
+	fi
+}
+
+trap kill_steam TERM
+
+wait "$steam_wrapper_pid"
+exit_code=$?
+
+trap - TERM
+
+if (( exit_code > 128 )); then
+	wait "$steam_wrapper_pid"
 fi
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
@@ -350,19 +411,16 @@ else
 	rm "$short_session_tracker_file"
 fi
 
-# Ask gamescope to exit nicely
-kill $gamescope_pid
+# Ask all children to exit nicely, now that steam has exited
+readarray -t children < <(print_children $$)
 
-# Start a background sleep for five seconds because we don't trust it
-sleep 5 &
-sleep_pid=$!
+send_signals "${children[@]}"
 
-# Wait for gamescope or the sleep to finish for timeout purposes
-ret=0
-wait -n $gamescope_pid $sleep_pid || ret=$?
+cleanup 5 "${children[@]}"
+cleanup_status=$!
 
 # If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
-if [[ $ret = 127 ]]; then
+if (( cleanup_status == 1 )); then
 	echo >&2 "gamescope-session: Interrupted while waiting on teardown, force-killing remaining tasks"
 fi
 
@@ -370,14 +428,14 @@ fi
 # to exit in time or we hit the interrupt case above)
 for job in $(jobs -p); do
 	# Warn about unexpected things
-	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
+	if (( cleanup_status == 1 )) && [[ $job = "$gamescope_pid" ]]; then
 		echo >&2 "gamescope-session: gamescope timed out while exiting, killing"
-	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
+	elif (( cleanup_status == 1 )) && [[ $job != "$sleep_pid" ]]; then
 		echo >&2 "gamescope-session: unexpected background pid $job at teardown: "
 		# spew some debug about it
 		ps -p "$job" >&2
 	fi
-	kill -9 "$job"
+	kill -KILL "$job"
 done
 
 # This should just be waiting on kill -9'd things. Another signal will cause us to give up, but we should be a little
