gamescope-3.13.16.9-1
Archive sha256sum: 89903c69bb51611b48815b149bea9d2d7670c5122aca4f9dc9adbbcc08c069f1 jupiter-3.9/gamescope-3.13.16.9-1.src.tar.gz

diff --git a/gamescope-session b/gamescope-session
--- a/gamescope-session
+++ b/gamescope-session
@@ -158,7 +158,6 @@ export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)
 export GAMESCOPE_DISABLE_ASYNC_FLIPS=1
 
 export XCURSOR_THEME=steam
-export XCURSOR_SCALE=256
 
 # Workaround for Steam login issue while Steam client change propagates out of Beta
 touch ~/.steam/root/config/SteamAppData.vdf || true
@@ -230,6 +229,14 @@ if [[ "$free_disk_space_megs" -lt "$minimum_free_disk_space_needed_megs" ]]; the
 	done
 fi
 
+# Will be empty if not on Galileo or failed
+mura_args=()
+mura_path=$(galileo-mura-setup)
+if [ $? -eq 0 ]; then
+	mura_args=("--mura-map" "$mura_path")
+fi
+
+
 export GAMESCOPE_STATS="$stats"
 mkfifo -- "$stats"
 mkfifo -- "$socket"
@@ -255,9 +262,10 @@ gamescope \
 	--hide-cursor-delay 3000 \
 	--max-scale 2 \
 	--fade-out-duration 200 \
-	--cursor-scale-height 720 \
 	-e -R "$socket" -T "$stats" \
 	-O '*',eDP-1 \
+	"${mura_args[@]}" \
+	--cursor-hotspot 5,3 --cursor /usr/share/steamos/steamos-cursor.png \
 	&
 gamescope_pid="$!"
 
@@ -285,9 +293,6 @@ steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
     /usr/lib/hwsupport/powerbuttond
 done) &
 
-(while true; do
-	/usr/lib/hwsupport/wakehook
-done) &
 
 short_session_tracker_file="/tmp/steamos-short-session-tracker"
 short_session_duration=60
@@ -310,16 +315,18 @@ if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
 	rm "$short_session_tracker_file"
 fi
 
+# This will re-send automount notifications for steam, and has a builtin timeout to wait for steam to come up.
+# _eventually_ steam should learn to talk to udisks so we don't have to rube goldberg this info to it.
+/usr/bin/steamos-polkit-helpers/steamos-retrigger-automounts
+
 if [[ -x $HOME/devkit-game/devkit-steam ]]; then
 	steam_notif_daemon &
-	galileo-mura-setup &
 	(while true; do
 		mangoapp
 	done) &
 	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
 else
 	steam_notif_daemon &
-	galileo-mura-setup &
 	(while true; do
 		mangoapp
 	done) &
