jupiter-legacy-support-1.157-1
Archive sha256sum: 953853cd7d90bf28db5fadf32eb3de067d61c69c9d80bd816c8636edfcb54cfc jupiter-main/jupiter-legacy-support-1.157-1.src.tar.gz

diff --git a/holo-prepare-oobe-test b/holo-prepare-oobe-test
--- a/holo-prepare-oobe-test
+++ b/holo-prepare-oobe-test
@@ -6,10 +6,10 @@ set -euo pipefail
 ## so we can test the flow of then updating from it to a day-1 update.
 
 # Usage:
-#   steamos-prepare-oobe-test
+#   holo-prepare-oobe-test
 #   # Optionally also arm the factory reset machinery to get a 'clean' install into the factory image, for more thorough
 #   # testing
-#   steamos-factory-reset-config
+#   holo-factory-reset-config
 #   # Reboot into new factory image, which will 'update' back to the latest stable image.
 #   reboot
 
@@ -44,11 +44,11 @@ log "Target OOBE image: $url"
 ## Do the install
 log "Installing '$url' to other slot"
 
-cmd steamos-atomupd-client -d --update-from-url="$url" || die "Install failed, see above."
+cmd atomupd-manager custom-update "$url" --verbose || die "Install failed, see above."
 
 if [[ -n $arg_clean ]]; then
   log "--clean specified, removing network configurations from remote side"
-  cmd steamos-chroot --partset other -- rm -rf /var/lib/overlays/etc/upper/NetworkManager/ /var/lib/iwd/
+  cmd holo-chroot --partset other -- rm -rf /var/lib/overlays/etc/upper/NetworkManager/ /var/lib/iwd/
 fi
 
 log "Other slot has been updated to $url and ready to be used as a OOBE image test"
@@ -56,4 +56,4 @@ log
 log "  Run \`reboot\` to boot into the OOBE, which will perform a day one update."
 log
 log "  To abort rebooting into the OOBE and retain the current update, run:"
-log "    sudo steamos-bootconf set-mode reboot"
+log "    sudo holo-bootconf set-mode reboot"
