steamos-networking-tools-1.2-1
Archive sha256sum: b5e53eaec1c031e5e7c8031205d75220561746265f62a8054fd431f36cd2fef2 holo-main/steamos-networking-tools-1.2-1.src.tar.gz

diff --git a/steamos-wifi-set-backend-privileged b/steamos-wifi-set-backend-privileged
--- a/steamos-wifi-set-backend-privileged
+++ b/steamos-wifi-set-backend-privileged
@@ -19,10 +19,22 @@ fi
 declare -r NM_WIFI_BACKEND_CONF_FILE="/etc/NetworkManager/conf.d/99-valve-wifi-backend.conf"
 
 
+validate_backend() {
+    case "$1" in
+        "iwd"|"wpa_supplicant")
+            ;;
+        *)
+            echo >&2 "ERROR: '$1' is not a valid backend"
+            exit 1
+        ;;
+    esac
+}
+
 write_config_wifi_backend() {
     local desired_backend="$1"
+    validate_backend "$1"
 
-    sed -i "s/^wifi.backend[ \t]*=.*$/wifi.backend=${desired_backend}/" "${NM_WIFI_BACKEND_CONF_FILE}"
+    echo -e "[device]\nwifi.backend=${desired_backend}" > "${NM_WIFI_BACKEND_CONF_FILE}"
 }
 
 
@@ -80,6 +92,7 @@ case "${1}" in
     restart_units)
         other_backend="$2"
         {
+            validate_backend "${other_backend}"
             systemctl stop NetworkManager
             systemctl disable --now "${other_backend}"
             # these systemd units are not set to enabled permanently, NetworkManager will pull them as necessary
