steamos-systemreport-0.21-1
Archive sha256sum: 6d0b14b6a7fc4c81e5ff637f8b0a4d434dad4dc1e8f22d64dfee3146070478dc holo-3.9/steamos-systemreport-0.21-1.src.tar.gz

diff --git a/steamos-systemreport b/steamos-systemreport
--- a/steamos-systemreport
+++ b/steamos-systemreport
@@ -54,7 +54,7 @@ function run {
   echo "---------------------------------------------------"
   echo "Command: $1"
   echo
-  bash -c "$1 2>&1" || echo "Unable to run command!"
+  PAGER=cat SYSTEMD_PAGER=cat bash -c "$1 2>&1" || echo "Unable to run command!"
 }
 
 function super () {
