steamos-networking-tools-1.3-1
Archive sha256sum: e926efc911bd5f958d41191ad2beac9904d4be35666a32170cab557b0e579605 holo-main/steamos-networking-tools-1.3-1.src.tar.gz

diff --git a/steamos-wifi-set-backend-privileged b/steamos-wifi-set-backend-privileged
--- a/steamos-wifi-set-backend-privileged
+++ b/steamos-wifi-set-backend-privileged
@@ -74,7 +74,9 @@ write_config_wifi_backend() {
 ensure_default_interface() {
     if ! iw dev wlan0 info &>/dev/null; then
         echo 'INFO: missing wlan0, creating it explicitly'
-        iw phy phy0 interface add wlan0 type station
+        if ! iw phy phy0 interface add wlan0 type station; then
+            echo >&2 'ERROR: cannot add wlan0 to phy0, possibly system without WiFi hardware'
+        fi
         sleep 1s
         if ! iw dev wlan0 info &>/dev/null; then
             echo >&2 'ERROR: wlan0 could not be created'
