gamescope-3.16.4-2
Archive sha256sum: 826893e7ae4aef5aa075a780f8023daa0f243d5f6715db95ba7737fdb67f0bab jupiter-main/gamescope-3.16.4-2.src.tar.gz

diff --git a/steam-short-session-tracker b/steam-short-session-tracker
--- a/steam-short-session-tracker
+++ b/steam-short-session-tracker
@@ -5,53 +5,65 @@ short_session_start_file="/tmp/steamos-short-session-start"
 short_session_duration=60
 short_session_count_before_reset=3
 
-handle_started() {
-    short_session_count=$(< "$short_session_tracker_file" wc -l)
-    touch $short_session_start_file
+do_repair() {
+  # This should really be part of the steam launcher as `steam --repair` or similar, but we presently only have
+  # `steam --reset` which is too heavy of a hammer.
 
-    if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-        echo >&2 "gamescope-session: detected broken Steam, bootstrapping from OS copy..."
-        # at this point, might as well make sure we won't relaunch on a sideloaded build
-        rm -f -- "$HOME/devkit-game/devkit-steam"
-        mkdir -p ~/.local/share/Steam
-        # remove some caches and stateful things known to cause Steam to fail to start if corrupt
-        rm -rf --one-file-system ~/.local/share/Steam/config/widevine
-        # cleanup the steam config dir, i.e. ~/.steam. We should try to preserve registry.vdf if possible
-        steam_config_dir="$HOME/.steam"
-        steam_config_backup_dir="$HOME/dot-steam.bak.$(date +%s)"
-        registry_vdf="$steam_config_dir/registry.vdf"
-        registry_backup_vdf="$steam_config_backup_dir/.steam/registry.vdf"
-        mv "$steam_config_dir" "$steam_config_backup_dir"
-        mkdir -p "$steam_config_dir"
-        cp -f "$registry_backup_vdf" "$registry_vdf" || true
-        # restore clean copy of binaries from RO partition
-        tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
-        # rearm
-        rm "$short_session_tracker_file"
-    fi
+  echo >&2 "steam-short-session-tracker: Re-bootstrapping steam from OS copy."
+  # at this point, might as well make sure we won't relaunch on a sideloaded build
+  rm -f -- "$HOME/devkit-game/devkit-steam"
+  mkdir -p ~/.local/share/Steam
+  # remove some caches and stateful things known to cause Steam to fail to start if corrupt
+  rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+  # cleanup the steam config dir, i.e. ~/.steam. We should try to preserve registry.vdf if possible
+  steam_config_dir="$HOME/.steam"
+  steam_config_backup_dir="$HOME/dot-steam.bak.$(date +%s)"
+  registry_vdf="$steam_config_dir/registry.vdf"
+  registry_backup_vdf="$steam_config_backup_dir/.steam/registry.vdf"
+  mv "$steam_config_dir" "$steam_config_backup_dir"
+  mkdir -p "$steam_config_dir"
+  cp -f "$registry_backup_vdf" "$registry_vdf" || true
+  # restore clean copy of binaries from RO partition
+  tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
+  # rearm
+  rm "$short_session_tracker_file"
+}
+
+handle_started() {
+  short_session_count=$(< "$short_session_tracker_file" wc -l)
+  touch $short_session_start_file
+
+  if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
+    echo >&2 "steam-short-session-tracker: Steam failed to start $short_session_count_before_reset times within $short_session_duration seconds"
+
+    do_repair
+  fi
 }
 
 handle_stopped() {
-    seconds_since_started=$(($(date +%s) - $(date +%s -r "$short_session_start_file")))
+  seconds_since_started=$(($(date +%s) - $(date +%s -r "$short_session_start_file")))
 
-    if [[ "seconds_since_started" -lt "$short_session_duration" ]]; then
-        echo "frog" >> "$short_session_tracker_file"
-    else
-        rm "$short_session_tracker_file"
-    fi
+  if [[ "seconds_since_started" -lt "$short_session_duration" ]]; then
+    echo "frog" >> "$short_session_tracker_file"
+  else
+    rm "$short_session_tracker_file"
+  fi
 }
 
 case "$1" in
-    --started)
-        handle_started
-        ;;
-    --stopped)
-        handle_stopped
-        ;;
-    *)
-        echo "Usage: $0 --started | --stopped"
-        exit 1
-        ;;
+  --track-started)
+    handle_started
+    ;;
+  --track-stopped)
+    handle_stopped
+    ;;
+  --repair-now)
+    do_repair
+    ;;
+  *)
+    echo "Usage: $0 --track-started | --track-stopped | --repair-now"
+    exit 1
+    ;;
 esac
 
 exit 0
